"""commissions, media and measurements

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 22:09:26.817805
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dog_name', sa.String(length=120), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('pose', sa.String(length=60), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=40), nullable=False),
    sa.Column('vet', sa.String(length=240), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commissions'))
    )
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commissions_token'), ['token'], unique=True)

    op.create_table('measurement_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('unit', sa.String(length=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('nose_to_tail', sa.Float(), nullable=True),
    sa.Column('withers_height', sa.Float(), nullable=True),
    sa.Column('chest_girth', sa.Float(), nullable=True),
    sa.Column('neck', sa.Float(), nullable=True),
    sa.Column('head_length', sa.Float(), nullable=True),
    sa.Column('head_width', sa.Float(), nullable=True),
    sa.Column('front_paw_width', sa.Float(), nullable=True),
    sa.Column('front_paw_length', sa.Float(), nullable=True),
    sa.Column('rear_paw_width', sa.Float(), nullable=True),
    sa.Column('rear_paw_length', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name=op.f('fk_measurement_sets_commission_id_commissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurement_sets'))
    )
    with op.batch_alter_table('measurement_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_sets_commission_id'), ['commission_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], name=op.f('fk_media_commission_id_commissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('stored_name', name=op.f('uq_media_stored_name'))
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_commission_id'), ['commission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_commission_id'))

    op.drop_table('media')
    with op.batch_alter_table('measurement_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_sets_commission_id'))

    op.drop_table('measurement_sets')
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissions_token'))

    op.drop_table('commissions')
    # ### end Alembic commands ###
